---

- name: Directories created
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ traefik_app_dir }}"
    - "{{ traefik_app_config_dir }}"
    - "{{ traefik_log_dir }}"
  become: true

- name: Config file created
  ansible.builtin.template:
    src: traefik.yaml.j2
    dest: "{{ traefik_config_path }}"
    mode: "0755"
  become: true

- name: Traefik container started
  community.docker.docker_container:
    image: "{{ traefik_image }}"
    pull: true
    name: traefik
    restart_policy: unless-stopped
    detach: true
    restart: true
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    mounts:
      - type: bind
        source: "{{ traefik_app_config_dir }}"
        target: /etc/traefik/
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`{{ traefik_host_name }}`)"
      traefik.http.routers.traefik.entrypoints: "websecure"
      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.tls.certresolver: letsEncryptResolver
      traefik.http.routers.traefik.service: api@internal
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
